import React from 'react';

const Post = () => {

    return (
        <div>
            <h1>tiitel</h1>
            <div className="post-thumb"><img src="http://dummyimage.com/200x200/f0f/fff" /></div>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dui arcu. Pellentesque sollicitudin lorem consectetur sapien feugiat posuere. Mauris porta efficitur magna quis varius. Vestibulum efficitur fermentum neque nec ornare. Donec sollicitudin bibendum metus vitae dignissim. Sed posuere leo nec nisi placerat, at convallis orci ultrices. Morbi condimentum convallis dolor, sit amet congue tellus hendrerit et. Curabitur porta vulputate dui ut viverra. Curabitur imperdiet purus sollicitudin, vehicula lorem et, iaculis libero. In venenatis venenatis ex dictum dictum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dui arcu. Pellentesque sollicitudin lorem consectetur sapien feugiat posuere. Mauris porta efficitur magna quis varius. Vestibulum efficitur fermentum neque nec ornare. Donec sollicitudin bibendum metus vitae dignissim. Sed posuere leo nec nisi placerat, at convallis orci ultrices. Morbi condimentum convallis dolor, sit amet congue tellus hendrerit et. Curabitur porta vulputate dui ut viverra. Curabitur imperdiet purus sollicitudin, vehicula lorem et, iaculis libero. In venenatis venenatis ex dictum dictum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dui arcu. Pellentesque sollicitudin lorem consectetur sapien feugiat posuere. Mauris porta efficitur magna quis varius. Vestibulum efficitur fermentum neque nec ornare. Donec sollicitudin bibendum metus vitae dignissim. Sed posuere leo nec nisi placerat, at convallis orci ultrices. Morbi condimentum convallis dolor, sit amet congue tellus hendrerit et. Curabitur porta vulputate dui ut viverra. Curabitur imperdiet purus sollicitudin, vehicula lorem et, iaculis libero. In venenatis venenatis ex dictum dictum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dui arcu. Pellentesque sollicitudin lorem consectetur sapien feugiat posuere. Mauris porta efficitur magna quis varius. Vestibulum efficitur fermentum neque nec ornare. Donec sollicitudin bibendum metus vitae dignissim. Sed posuere leo nec nisi placerat, at convallis orci ultrices. Morbi condimentum convallis dolor, sit amet congue tellus hendrerit et. Curabitur porta vulputate dui ut viverra. Curabitur imperdiet purus sollicitudin, vehicula lorem et, iaculis libero. In venenatis venenatis ex dictum dictum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dui arcu. Pellentesque sollicitudin lorem consectetur sapien feugiat posuere. Mauris porta efficitur magna quis varius. Vestibulum efficitur fermentum neque nec ornare. Donec sollicitudin bibendum metus vitae dignissim. Sed posuere leo nec nisi placerat, at convallis orci ultrices. Morbi condimentum convallis dolor, sit amet congue tellus hendrerit et. Curabitur porta vulputate dui ut viverra. Curabitur imperdiet purus sollicitudin, vehicula lorem et, iaculis libero. In venenatis venenatis ex dictum dictum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dui arcu. Pellentesque sollicitudin lorem consectetur sapien feugiat posuere. Mauris porta efficitur magna quis varius. Vestibulum efficitur fermentum neque nec ornare. Donec sollicitudin bibendum metus vitae dignissim. Sed posuere leo nec nisi placerat, at convallis orciultrices. Morbi condimentum convallis dolor, sit amet congue tellus hendrerit et. Curabitur porta vulputate dui ut viverra. Curabitur imperdiet purus sollicitudin, vehicula lorem et, iaculis libero. In venenatis venenatis ex dictum dictum.
        </div>
    );
}

export default Post;
